### PR TITLE
add force single line option

### PR DESCRIPTION
**Pull request by haomingw**

### CODE REVIEW

**Review by zzzeek — CHANGES_REQUESTED** [review]
hi there -

a few changes.

first can we call this --no-single-lines and reverse the default behavior, since I have all of my infra built out on not having this option and it also is backwards compatible.

second, can you add test files to test_files/,   multi_line.py and multi_line_expected.py, then add a test runner function in tests.py, you'll have to specify the new option using `_assert_file("multi_line.py", opts=("--no-single=line", ))`.  thanks!

**Comment by haomingw** [comment]
Hi @zzzeek, I added the test cases as you requested. Besides, can we call this option `--multi-imports` since you also have a function called `_as_single_imports`? If enabled, it doesn't change existing single imports. I will change the option name if you think others would be better.

**Comment by zzzeek** [comment]
I don't understand how this feature is supposed to work.

what if I have:

```
from . import foo, bar
from . import cat, loop
```

what would the order be?     it has to follow one of the orderings at https://github.com/PyCQA/flake8-import-order, and some of those support multiple names on one line but they are still sorted alphabetically across a certain name.

**Comment by zzzeek** [comment]
also, i definitely need it to break up lines by default.   this tool is first and foremost for the sqlalchemy projects.

**Comment by haomingw** [comment]
Hi @zzzeek, by default it breaks up line, I didn't change that behavior since the first commit. For your test case, imports of each line is sorted alphabetically, for example, `import foo, bar` becomes `import bar, foo`. The order between the lines is determined by your `sort_imports` function, which I think applies the ordering defined by style. I modified the test case to make it clear.

**Comment by haomingw** [comment]
According to my understanding,
```
parser.add_argument(
    "--multi-imports",
    action="store_true",
    help="If set, multiple imports can exist on one line"
)
```
means only when we do `--multi-imports`, the attribute `multi_imports` becomes true. We do not pass this argument by default, so `multi_imports`'s default value is false.

**Comment by zzzeek** [comment]
neat seems to work

**Comment by zzzeek** [comment]
thanks!  I squashed and released 0.2.0.

**Pull request closed without merging**
