### PR TITLE
Use stdin/stdout when the filename is "-"

### PR DESCRIPTION
**Pull request by schmir**
Previously one could use 'zimports --stdout /dev/stdin' to read from
stdin and write to stdout. This at least worked on Linux.

With this commit we support "-" as filename, which makes zimports read
from stdin and write to stdout.

### CODE REVIEW

**Comment by zzzeek** [comment]
very nice, works great!

**Comment by zzzeek** [comment]
also I apologize that zimports does not have a changelog as of yet.   for the moment the changes in github sort of serve that purpose :/

**Comment by schmir** [comment]
that's not a problem for me. but, can we have a new release on PyPI?

**Comment by zzzeek** [comment]
ok that is up 0.2.2

**Pull request merged**
